apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: meetup
  name: meetup
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: meetup
    spec:
      containers:
      - name: meetup
        image: ipedrazas/meetup:sydney
        imagePullPolicy: Always
        env:
          - name: VAULT_ADDR
            value: http://vault:9000
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault
                key: token
        volumeMounts:
             - name: credentials-from-vault
               mountPath: /credentials

      - name: vault-side-kick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.0.9-2
        args:
          - -output=/credentials
          - -cn=secret:secret/sydney:file=app.json
        env:
          - name: VAULT_ADDR
            value: http://vault:9000
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: vault
                key: token
        volumeMounts:
          - name: credentials-from-vault
            mountPath: /credentials
      volumes:
        - name: credentials-from-vault
          emptyDir: {}