
apiVersion: v1
kind: Service
metadata:
  name: meetup
  labels:
    name: meetup
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: meetup