apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: LoadBalancer
  ports:
    - port: 9000
  selector:
    app: vault
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vault        
    spec:
      containers:
      - image: ipedrazas/vault
        name: vault        
        ports:
        - containerPort: 9000
          name: vault